### ISSUE TITLE
LDAP plugin and Mirth 3.11

### ISSUE THREAD

**Issue by alcir** [ChristopherSchultz/mirth-plugins#4]
Does it work with Mirth 3.11 (well, Mirth > 3.8) or does it work with 3.8 only?

**Comment by alcir** [comment]
Ok, the answer is: it doesn't work.
Is it difficult to build it versus Mirth 3.11?

**Comment by jonbartels** [comment]
> Is it difficult to build it versus Mirth 3.11?

Plugins are generally compatible across MC versions. 

1. Update the MC dependencies in https://github.com/ChristopherSchultz/mirth-plugins/blob/master/ldap-auth/pom.xml
2. Since you're touching the POM anyway add a repo entry to an open-source repo for the MC libraries (saves the hassle of downloading them separately). Look at the karuplang repo example at https://github.com/kpalang/mirth-transmissionmode-cube30touch/blob/master/pom.xml
3. Add the new version to https://github.com/ChristopherSchultz/mirth-plugins/blob/master/ldap-auth/src/main/resources/plugin.xml
4. Do a build and fix any plugin errors
5. test the functionality in your MC

**Comment by jonbartels** [comment]
Oh almost forgot 

6. Issue a pull-request with your updates if you can. It will help the next person!

**Comment by alcir** [comment]
Ok, I simply added `3.11.0` to `src/main/resources/plugin.xml`
Then I copied to `libs/` the files `mirth-client-core.jar`, `mirth-client.jar`, `mirth-server.jar` (grabbed from Mirth 3.8.0, because maven throws some errors with those from 3.11.0).
I uploaded and installed the resulting zip file from the GUI. And it works.

**Comment by Matakaheru** [comment]
Ok, I just want to be sure here .... we build with 'mvn package' correct? The author talks about a .zip file, and now alcir mentions a resulting .zip file. My target is a .jar file .... how am I going wrong here?

**Comment by ChristopherSchultz** [comment]
It's "complicated" because Mirth plug-ins are _not_ just .jar libraries. You don't put this into your `custom-lib/` directory and restart the server. Instead, you have to either "install" the plug-in via the MC Admin interface by uploading a ZIP file, or you need to drop the ZIP file into the plugins directory if you are deploying manually.

In either case, the plug-in *is* a ZIP file. It contains (a) the server .jar library, (b) the client .jar library, and (c) the plug-in description file which XML.

**Comment by ChristopherSchultz** [comment]
If you just want to compile and get .jar files, then mvn package is what you want. But that doesn't build a plug-in. You need to bundle the plug-in into a ZIP file and you also need to cryptographically-sign the JAR files so the Mirth Admin client will load them.

If you read (and then run) the "bundle.sh" script, you'll see what needs to be done.

You will need to mint your own key and certificate for signing. I can build a signed package for you, but you'll have to trust that I haven't put some evil stuff into it. It's easier if you just built it yourself and then you know what you've got.

**Comment by Matakaheru** [comment]
So I need to run the bundle.sh script? Sorry, that wasn't clear to me. I'll run that one.
